name: CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install flake8 pytest
      - name: Lint with flake8
        run: flake8 scripts/*.py --count --show-source --statistics
      - name: Run tests
        run: pytest tests/
      - name: Run agent script
        run: python scripts/agent.py
